[package]
name = "triton-grpc-proxy"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
authors = ["kozistr <kozistr@gmail.com>"]
description = "proxy server for triton gRPC inference server"
homepage = "https://github.com/kozistr/triton-grpc-proxy"
readme = "README.md"
repository = "https://github.com/kozistr/triton-grpc-proxy"
categories = ["proxy", "triton"]
keywords = ["proxy", "triton", "grpc"]

[features]
default = ["tls"]
tls = ["tonic/tls", "tonic/tls-roots"]

[dependencies]
bytes = { version = "1", default-features = false }
prost = { version = "^0.12", default-features = false, features = ["prost-derive"] }
prost-types = { version = "^0.12", default-features = false }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0"
tonic = { version = "^0.9.2", default-features = false, features = ["codegen", "prost"] }
thiserror = "1.0"
anyhow = "1.0"
http = { version = "0.2", default-features = false }
http-body = { version = "0.4", default-features = false }
byteorder = { version = "1", default-features = false }
base64 = { version = "0.21", default-features = false }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
js-sys = { version = "0.3", default-features = false }
httparse = { version = "1", default-features = false }
hyper = { version = "0.14", default-features = false }
wasm-bindgen = { version = "0.2", default-features = false, features = ["serde-serialize"] }
wasm-bindgen-futures = { version = "0.4", default-features = false }
wasm-streams = { version = "0.2" }

[build-dependencies]
walkdir = "2"
anyhow = "1.0"
tonic-build = "^0.9.2"

[profile.dev]
incremental = true
opt-level = 0
codegen-units = 4
lto = false
panic = "unwind"
debug = true
debug-assertions = true
overflow-checks = false
rpath = false

[profile.release]
incremental = true
opt-level = 3
codegen-units = 1
lto = "fat"
panic = "abort"
debug = false
debug-assertions = false
overflow-checks = false
rpath = false
