[package]
name = "triton-grpc-proxy"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
authors = ["kozistr <kozistr@gmail.com>"]
description = "proxy server for triton gRPC inference server"
homepage = "https://github.com/kozistr/triton-grpc-proxy"
readme = "README.md"
repository = "https://github.com/kozistr/triton-grpc-proxy"
categories = ["proxy", "triton"]
keywords = ["proxy", "triton", "grpc"]

[dependencies]
anyhow = "^1.0.75"
tonic = "^0.9.2"
tokio = { version = "^1.32.0", features = ["macros", "rt-multi-thread"] }
triton-client = { git = "https://github.com/octoml/triton-client-rs.git" }

[build-dependencies]

[profile.dev]
incremental = true
opt-level = 0
codegen-units = 4
lto = false
panic = "unwind"
debug = true
debug-assertions = true
overflow-checks = false
rpath = false

[profile.release]
incremental = true
opt-level = 3
codegen-units = 1
lto = "fat"
panic = "abort"
debug = false
debug-assertions = false
overflow-checks = false
rpath = false
