tab_spaces = 4
hard_tabs = false
edition = "2021"
# max_width = 100
# array_width = 60
# chain_width = 60
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
match_block_trailing_comma = true
use_small_heuristics = "Max"

unstable_features = true
imports_granularity = "Module"
condense_wildcard_suffixes = true
wrap_comments = true
comment_width = 100
brace_style = "SameLineWhere"
format_code_in_doc_comments = true
# format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
reorder_impl_items = true
# reorder_imports = true
# reorder_modules = true
normalize_doc_attributes = true
normalize_comments = true
version = "Two"
